# Generated by Django 3.1.6 on 2022-03-24 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('team_number', models.IntegerField()),
                ('nickname', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
