# Generated by Django 3.1.6 on 2022-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20220325_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='auto_high_cargo_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='auto_low_cargo_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='auto_score_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='auto_shoot_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='crossed_scoring_line_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='end_points_scored_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='failed_climb_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='first_rung_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='one_ball_start_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='participation_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='second_rung_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_against_hub_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_attempted_shot_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_carpet_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_defense_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_defense_effective_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_effective_floor_pickup_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_launch_pad_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_missed_shot_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_pickup_floor_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_pickup_human_player_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_scores_cargo_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='teleop_tarmac_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_match_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='traversal_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='zero_ball_start_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
