# Generated by Django 3.1.6 on 2022-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20220325_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='climb_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
