# Generated by Django 3.1.6 on 2022-03-24 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('PRACTICE', 'Practice'), ('QUALIFICATION', 'Qualification'), ('PLAYOFF', 'Playoff')], max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
