# Generated by Django 3.1.6 on 2022-03-24 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220324_1328'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.CreateModel(
            name='ScoutedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alliance', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], max_length=255)),
                ('scouted_by', models.CharField(max_length=255)),
                ('did_participate', models.BooleanField()),
                ('auto_cargo_start_count', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('auto_does_cross_scoring_line', models.BooleanField()),
                ('auto_does_shoot', models.BooleanField()),
                ('auto_does_score_cargo', models.BooleanField()),
                ('auto_cargo_scored', models.IntegerField(default=0)),
                ('teleop_where_get_cargo', models.CharField(choices=[('FLOOR', 'Floor'), ('HUMAN PLAYER', 'Human Player'), ('N/A', 'N/A')], max_length=255)),
                ('teleop_effective_floor_cargo', models.BooleanField()),
                ('teleop_does_score_cargo', models.BooleanField()),
                ('teleop_cargo_score_location', models.CharField(choices=[('UPPER GOAL', 'Upper Goal'), ('LOWER GOAL', 'Lower Goal'), ('BOTH GOALS', 'Both Goals'), ('N/A', 'N/A')], max_length=255)),
                ('teleop_attempted_shots', models.IntegerField(default=0)),
                ('teleop_missed_shots', models.IntegerField(default=0)),
                ('teleop_can_shoot_launch_pad', models.BooleanField()),
                ('teleop_can_shoot_tarmac', models.BooleanField()),
                ('teleop_can_shoot_carpet', models.BooleanField()),
                ('teleop_can_shoot_against_hub', models.BooleanField()),
                ('teleop_does_play_defense', models.BooleanField()),
                ('teleop_defense_effective', models.BooleanField()),
                ('end_does_climb', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('FAILED', 'Failed')], max_length=255)),
                ('end_climb_first_rung', models.BooleanField()),
                ('end_climb_second_rung', models.BooleanField()),
                ('end_climb_traversal', models.BooleanField()),
                ('end_points_scored', models.IntegerField()),
                ('notes', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
