# Generated by Django 3.1.6 on 2022-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20220324_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutedmatch',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
